//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemessaBB.FUNAF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PGEDBAgent2")]
        public string PathToWatch {
            get {
                return ((string)(this["PathToWatch"]));
            }
            set {
                this["PathToWatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00")]
        public string HorarioProcessamento {
            get {
                return ((string)(this["HorarioProcessamento"]));
            }
            set {
                this["HorarioProcessamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.c279452</string>
  <string>.c221534</string>
  <string>.c2815189</string>
  <string>.c37950000005480</string>
  <string>.c37950000005011</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExtensoesParaTratar {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExtensoesParaTratar"]));
            }
            set {
                this["ExtensoesParaTratar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>retorno/</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DiretoriosParaDownload {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DiretoriosParaDownload"]));
            }
            set {
                this["DiretoriosParaDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("remessa/")]
        public string DiretoriosParaUpload {
            get {
                return ((string)(this["DiretoriosParaUpload"]));
            }
            set {
                this["DiretoriosParaUpload"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.104.13.8;Initial Catalog=pge;Persist Security Info=True;User ID=sa" +
            ";Password=admin!Q@W#E")]
        public string AppConnectionString {
            get {
                return ((string)(this["AppConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1QAw3edr5")]
        public string FTPSenha {
            get {
                return ((string)(this["FTPSenha"]));
            }
            set {
                this["FTPSenha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.liketecnologia.net/")]
        public string FTPHost {
            get {
                return ((string)(this["FTPHost"]));
            }
            set {
                this["FTPHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("like")]
        public string FTPLogin {
            get {
                return ((string)(this["FTPLogin"]));
            }
            set {
                this["FTPLogin"] = value;
            }
        }
    }
}
