//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funaf.Web.Api.wsAutenticar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pge.rn.gov.br/sigues", ConfigurationName="wsAutenticar.WsSiGUeSSoap")]
    public interface WsSiGUeSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/AcaoProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Acao AcaoProcessar(Funaf.Web.Api.wsAutenticar.Acao acao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/AcaoProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Acao> AcaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Acao acao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/AuditoriaProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Auditoria AuditoriaProcessar(Funaf.Web.Api.wsAutenticar.Auditoria auditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/AuditoriaProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Auditoria> AuditoriaProcessarAsync(Funaf.Web.Api.wsAutenticar.Auditoria auditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/OrgaoProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Orgao OrgaoProcessar(Funaf.Web.Api.wsAutenticar.Orgao Orgao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/OrgaoProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Orgao> OrgaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Orgao Orgao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/PerfilProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Perfil PerfilProcessar(Funaf.Web.Api.wsAutenticar.Perfil perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/PerfilProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Perfil> PerfilProcessarAsync(Funaf.Web.Api.wsAutenticar.Perfil perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/PermissaoProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Permissao PermissaoProcessar(Funaf.Web.Api.wsAutenticar.Permissao permissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/PermissaoProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Permissao> PermissaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Permissao permissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/RelacionamentoProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Relacionamento RelacionamentoProcessar(Funaf.Web.Api.wsAutenticar.Relacionamento relacionamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/RelacionamentoProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Relacionamento> RelacionamentoProcessarAsync(Funaf.Web.Api.wsAutenticar.Relacionamento relacionamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/SetorProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Setor SetorProcessar(Funaf.Web.Api.wsAutenticar.Setor Setor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/SetorProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Setor> SetorProcessarAsync(Funaf.Web.Api.wsAutenticar.Setor Setor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/SistemaProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Sistema SistemaProcessar(Funaf.Web.Api.wsAutenticar.Sistema sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/SistemaProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Sistema> SistemaProcessarAsync(Funaf.Web.Api.wsAutenticar.Sistema sistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/StatusProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Status StatusProcessar(Funaf.Web.Api.wsAutenticar.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/StatusProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Status> StatusProcessarAsync(Funaf.Web.Api.wsAutenticar.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/ServentiaProcessar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSistema))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPerfil))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfSetor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfOrgao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfTokenAuth))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfServentia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfRelacionamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfPermissao))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAuditoria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessObjectOfAcao))]
        Funaf.Web.Api.wsAutenticar.Serventia ServentiaProcessar(Funaf.Web.Api.wsAutenticar.Serventia Serventia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pge.rn.gov.br/sigues/ServentiaProcessar", ReplyAction="*")]
        System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Serventia> ServentiaProcessarAsync(Funaf.Web.Api.wsAutenticar.Serventia Serventia);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Acao : BusinessObjectOfAcao {
        
        private string txAcaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txAcao {
            get {
                return this.txAcaoField;
            }
            set {
                this.txAcaoField = value;
                this.RaisePropertyChanged("txAcao");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Acao))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfAcao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Acao[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Acao[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sistema))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfSistema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Sistema[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Sistema[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Sistema : BusinessObjectOfSistema {
        
        private string txSistemaField;
        
        private string txSiglaField;
        
        private Status statusField;
        
        private string txDescricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txSistema {
            get {
                return this.txSistemaField;
            }
            set {
                this.txSistemaField = value;
                this.RaisePropertyChanged("txSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string txSigla {
            get {
                return this.txSiglaField;
            }
            set {
                this.txSiglaField = value;
                this.RaisePropertyChanged("txSigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string txDescricao {
            get {
                return this.txDescricaoField;
            }
            set {
                this.txDescricaoField = value;
                this.RaisePropertyChanged("txDescricao");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Status : BusinessObjectOfStatus {
        
        private string txStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txStatus {
            get {
                return this.txStatusField;
            }
            set {
                this.txStatusField = value;
                this.RaisePropertyChanged("txStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Status))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Status[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Status[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Perfil))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfPerfil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Perfil[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Perfil[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Perfil : BusinessObjectOfPerfil {
        
        private string txPerfilField;
        
        private int idServentiaField;
        
        private int idSistemaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txPerfil {
            get {
                return this.txPerfilField;
            }
            set {
                this.txPerfilField = value;
                this.RaisePropertyChanged("txPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int idServentia {
            get {
                return this.idServentiaField;
            }
            set {
                this.idServentiaField = value;
                this.RaisePropertyChanged("idServentia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int idSistema {
            get {
                return this.idSistemaField;
            }
            set {
                this.idSistemaField = value;
                this.RaisePropertyChanged("idSistema");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Setor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfSetor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Setor[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Setor[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Setor : BusinessObjectOfSetor {
        
        private Orgao orgaoField;
        
        private string guIdADSetorField;
        
        private string txSetorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Orgao Orgao {
            get {
                return this.orgaoField;
            }
            set {
                this.orgaoField = value;
                this.RaisePropertyChanged("Orgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string guIdADSetor {
            get {
                return this.guIdADSetorField;
            }
            set {
                this.guIdADSetorField = value;
                this.RaisePropertyChanged("guIdADSetor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string txSetor {
            get {
                return this.txSetorField;
            }
            set {
                this.txSetorField = value;
                this.RaisePropertyChanged("txSetor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Orgao : BusinessObjectOfOrgao {
        
        private string txOrgaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txOrgao {
            get {
                return this.txOrgaoField;
            }
            set {
                this.txOrgaoField = value;
                this.RaisePropertyChanged("txOrgao");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Orgao))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfOrgao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Orgao[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Orgao[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TokenAuth))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfTokenAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private TokenAuth[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public TokenAuth[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class TokenAuth : BusinessObjectOfTokenAuth {
        
        private string txLoginField;
        
        private string txSenhaField;
        
        private int idSistemaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txLogin {
            get {
                return this.txLoginField;
            }
            set {
                this.txLoginField = value;
                this.RaisePropertyChanged("txLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string txSenha {
            get {
                return this.txSenhaField;
            }
            set {
                this.txSenhaField = value;
                this.RaisePropertyChanged("txSenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int idSistema {
            get {
                return this.idSistemaField;
            }
            set {
                this.idSistemaField = value;
                this.RaisePropertyChanged("idSistema");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serventia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfServentia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Serventia[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Serventia[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Serventia : BusinessObjectOfServentia {
        
        private TokenAuth tokenField;
        
        private string guIdField;
        
        private Status statusField;
        
        private Orgao orgaoField;
        
        private Setor setorField;
        
        private Perfil perfilField;
        
        private string guIdSetorField;
        
        private string txServentiaField;
        
        private string txContraSenhaField;
        
        private string txMatriculaField;
        
        private string txNomeField;
        
        private string txObservacoesField;
        
        private string txEmailField;
        
        private string txTelefoneField;
        
        private string txIpCadastroField;
        
        private bool isADField;
        
        private System.Nullable<System.DateTime> dtValidacaoField;
        
        private System.Nullable<System.DateTime> dtAcessoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TokenAuth Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string guId {
            get {
                return this.guIdField;
            }
            set {
                this.guIdField = value;
                this.RaisePropertyChanged("guId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Orgao Orgao {
            get {
                return this.orgaoField;
            }
            set {
                this.orgaoField = value;
                this.RaisePropertyChanged("Orgao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Setor Setor {
            get {
                return this.setorField;
            }
            set {
                this.setorField = value;
                this.RaisePropertyChanged("Setor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Perfil Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
                this.RaisePropertyChanged("Perfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string guIdSetor {
            get {
                return this.guIdSetorField;
            }
            set {
                this.guIdSetorField = value;
                this.RaisePropertyChanged("guIdSetor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string txServentia {
            get {
                return this.txServentiaField;
            }
            set {
                this.txServentiaField = value;
                this.RaisePropertyChanged("txServentia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string txContraSenha {
            get {
                return this.txContraSenhaField;
            }
            set {
                this.txContraSenhaField = value;
                this.RaisePropertyChanged("txContraSenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string txMatricula {
            get {
                return this.txMatriculaField;
            }
            set {
                this.txMatriculaField = value;
                this.RaisePropertyChanged("txMatricula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string txNome {
            get {
                return this.txNomeField;
            }
            set {
                this.txNomeField = value;
                this.RaisePropertyChanged("txNome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string txObservacoes {
            get {
                return this.txObservacoesField;
            }
            set {
                this.txObservacoesField = value;
                this.RaisePropertyChanged("txObservacoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string txEmail {
            get {
                return this.txEmailField;
            }
            set {
                this.txEmailField = value;
                this.RaisePropertyChanged("txEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string txTelefone {
            get {
                return this.txTelefoneField;
            }
            set {
                this.txTelefoneField = value;
                this.RaisePropertyChanged("txTelefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string txIpCadastro {
            get {
                return this.txIpCadastroField;
            }
            set {
                this.txIpCadastroField = value;
                this.RaisePropertyChanged("txIpCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool isAD {
            get {
                return this.isADField;
            }
            set {
                this.isADField = value;
                this.RaisePropertyChanged("isAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> dtValidacao {
            get {
                return this.dtValidacaoField;
            }
            set {
                this.dtValidacaoField = value;
                this.RaisePropertyChanged("dtValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> dtAcesso {
            get {
                return this.dtAcessoField;
            }
            set {
                this.dtAcessoField = value;
                this.RaisePropertyChanged("dtAcesso");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relacionamento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfRelacionamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Relacionamento[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Relacionamento[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Relacionamento : BusinessObjectOfRelacionamento {
        
        private string txRelacionamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txRelacionamento {
            get {
                return this.txRelacionamentoField;
            }
            set {
                this.txRelacionamentoField = value;
                this.RaisePropertyChanged("txRelacionamento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permissao))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfPermissao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Permissao[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Permissao[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Permissao : BusinessObjectOfPermissao {
        
        private Acao acaoField;
        
        private Relacionamento relacionamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Acao Acao {
            get {
                return this.acaoField;
            }
            set {
                this.acaoField = value;
                this.RaisePropertyChanged("Acao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Relacionamento Relacionamento {
            get {
                return this.relacionamentoField;
            }
            set {
                this.relacionamentoField = value;
                this.RaisePropertyChanged("Relacionamento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Auditoria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public abstract partial class BusinessObjectOfAuditoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string mensagemField;
        
        private int nuInstrucaoField;
        
        private bool isSucessfullField;
        
        private System.Nullable<System.DateTime> dtCadastroField;
        
        private string txValidacaoField;
        
        private Auditoria[] lsTodosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int nuInstrucao {
            get {
                return this.nuInstrucaoField;
            }
            set {
                this.nuInstrucaoField = value;
                this.RaisePropertyChanged("nuInstrucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isSucessfull {
            get {
                return this.isSucessfullField;
            }
            set {
                this.isSucessfullField = value;
                this.RaisePropertyChanged("isSucessfull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dtCadastro {
            get {
                return this.dtCadastroField;
            }
            set {
                this.dtCadastroField = value;
                this.RaisePropertyChanged("dtCadastro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string txValidacao {
            get {
                return this.txValidacaoField;
            }
            set {
                this.txValidacaoField = value;
                this.RaisePropertyChanged("txValidacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public Auditoria[] lsTodos {
            get {
                return this.lsTodosField;
            }
            set {
                this.lsTodosField = value;
                this.RaisePropertyChanged("lsTodos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pge.rn.gov.br/sigues")]
    public partial class Auditoria : BusinessObjectOfAuditoria {
        
        private Permissao permissaoField;
        
        private Serventia usuarioField;
        
        private Sistema sistemaField;
        
        private string txIpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Permissao Permissao {
            get {
                return this.permissaoField;
            }
            set {
                this.permissaoField = value;
                this.RaisePropertyChanged("Permissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Serventia Serventia {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Serventia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Sistema Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
                this.RaisePropertyChanged("Sistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string txIp {
            get {
                return this.txIpField;
            }
            set {
                this.txIpField = value;
                this.RaisePropertyChanged("txIp");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsSiGUeSSoapChannel : Funaf.Web.Api.wsAutenticar.WsSiGUeSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSiGUeSSoapClient : System.ServiceModel.ClientBase<Funaf.Web.Api.wsAutenticar.WsSiGUeSSoap>, Funaf.Web.Api.wsAutenticar.WsSiGUeSSoap {
        
        public WsSiGUeSSoapClient() {
        }
        
        public WsSiGUeSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSiGUeSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSiGUeSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSiGUeSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Funaf.Web.Api.wsAutenticar.Acao AcaoProcessar(Funaf.Web.Api.wsAutenticar.Acao acao) {
            return base.Channel.AcaoProcessar(acao);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Acao> AcaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Acao acao) {
            return base.Channel.AcaoProcessarAsync(acao);
        }
        
        public Funaf.Web.Api.wsAutenticar.Auditoria AuditoriaProcessar(Funaf.Web.Api.wsAutenticar.Auditoria auditoria) {
            return base.Channel.AuditoriaProcessar(auditoria);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Auditoria> AuditoriaProcessarAsync(Funaf.Web.Api.wsAutenticar.Auditoria auditoria) {
            return base.Channel.AuditoriaProcessarAsync(auditoria);
        }
        
        public Funaf.Web.Api.wsAutenticar.Orgao OrgaoProcessar(Funaf.Web.Api.wsAutenticar.Orgao Orgao) {
            return base.Channel.OrgaoProcessar(Orgao);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Orgao> OrgaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Orgao Orgao) {
            return base.Channel.OrgaoProcessarAsync(Orgao);
        }
        
        public Funaf.Web.Api.wsAutenticar.Perfil PerfilProcessar(Funaf.Web.Api.wsAutenticar.Perfil perfil) {
            return base.Channel.PerfilProcessar(perfil);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Perfil> PerfilProcessarAsync(Funaf.Web.Api.wsAutenticar.Perfil perfil) {
            return base.Channel.PerfilProcessarAsync(perfil);
        }
        
        public Funaf.Web.Api.wsAutenticar.Permissao PermissaoProcessar(Funaf.Web.Api.wsAutenticar.Permissao permissao) {
            return base.Channel.PermissaoProcessar(permissao);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Permissao> PermissaoProcessarAsync(Funaf.Web.Api.wsAutenticar.Permissao permissao) {
            return base.Channel.PermissaoProcessarAsync(permissao);
        }
        
        public Funaf.Web.Api.wsAutenticar.Relacionamento RelacionamentoProcessar(Funaf.Web.Api.wsAutenticar.Relacionamento relacionamento) {
            return base.Channel.RelacionamentoProcessar(relacionamento);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Relacionamento> RelacionamentoProcessarAsync(Funaf.Web.Api.wsAutenticar.Relacionamento relacionamento) {
            return base.Channel.RelacionamentoProcessarAsync(relacionamento);
        }
        
        public Funaf.Web.Api.wsAutenticar.Setor SetorProcessar(Funaf.Web.Api.wsAutenticar.Setor Setor) {
            return base.Channel.SetorProcessar(Setor);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Setor> SetorProcessarAsync(Funaf.Web.Api.wsAutenticar.Setor Setor) {
            return base.Channel.SetorProcessarAsync(Setor);
        }
        
        public Funaf.Web.Api.wsAutenticar.Sistema SistemaProcessar(Funaf.Web.Api.wsAutenticar.Sistema sistema) {
            return base.Channel.SistemaProcessar(sistema);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Sistema> SistemaProcessarAsync(Funaf.Web.Api.wsAutenticar.Sistema sistema) {
            return base.Channel.SistemaProcessarAsync(sistema);
        }
        
        public Funaf.Web.Api.wsAutenticar.Status StatusProcessar(Funaf.Web.Api.wsAutenticar.Status status) {
            return base.Channel.StatusProcessar(status);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Status> StatusProcessarAsync(Funaf.Web.Api.wsAutenticar.Status status) {
            return base.Channel.StatusProcessarAsync(status);
        }
        
        public Funaf.Web.Api.wsAutenticar.Serventia ServentiaProcessar(Funaf.Web.Api.wsAutenticar.Serventia Serventia) {
            return base.Channel.ServentiaProcessar(Serventia);
        }
        
        public System.Threading.Tasks.Task<Funaf.Web.Api.wsAutenticar.Serventia> ServentiaProcessarAsync(Funaf.Web.Api.wsAutenticar.Serventia Serventia) {
            return base.Channel.ServentiaProcessarAsync(Serventia);
        }
    }
}
